name: Download and release latest LIONS data 

on:
  push:

permissions:
  contents: write

jobs:
  run-and-release:
    runs-on: large-runner

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - name: Download data
        run: |
          mkdir -p inputs
          Rscript scripts/download_lions.R  

      - name: Unzip data
        run: |
          mkdir -p inputs/unzipped

          for z in inputs/*.[Zz][Ii][Pp]; do
            echo "Unzipping $z"
            basename=$(basename "$z")
            basename=${basename%.[Zz][Ii][Pp]}
            mkdir -p "inputs/unzipped/$basename"
            unzip -o "$z" -d "inputs/unzipped/$basename"
          done

      - name: Process data
        run: |
          mkdir -p outputs
          Rscript scripts/read_lions.R
          Rscript scripts/read_lions_D27.R
          Rscript scripts/read_lions_D28.R

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.LATEST_MONTH_TAG }} # Tagging with month so it's possible to check 
          name: "LIONS latest release ${{ env.LATEST_MONTH_NAME }}"
          artifacts: |
            outputs/*.feather
          generateReleaseNotes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
