name: Create Migration LIONS Data

on:
  push:

permissions:
  contents: write

jobs:
  run-and-release:
    runs-on: large-runner

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2

      - name: Download data
        run: |
          mkdir -p inputs
          Rscript scripts/filter_cases.R # This script creates a vector of UNIQUEIDs with any migration-related charge
     
      - name: Deidentify PII 
        run: |
          mkdir -p inputs
          Rscript scripts/mig_lions_data.R # This script creates dataset of migration-related cases and variables 
          
